# Generated by Django 2.0 on 2018-12-08 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(blank=True, null=True)),
                ('name', models.CharField(max_length=30, null=True)),
                ('inventory', models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(blank=True, null=True)),
                ('name', models.CharField(max_length=30, null=True)),
                ('inventory', models.PositiveIntegerField(blank=True, null=True)),
                ('related_components', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.Component')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(blank=True, null=True)),
                ('name', models.CharField(max_length=30, null=True)),
                ('inventory', models.PositiveIntegerField(blank=True, null=True)),
                ('components_required', models.ManyToManyField(blank=True, to='inventory.Component')),
            ],
        ),
    ]
