# Generated by Django 2.0 on 2018-12-08 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material',
            name='related_components',
        ),
        migrations.AddField(
            model_name='component',
            name='required_material',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.Material'),
        ),
    ]
