# Generated by Django 2.0 on 2018-12-17 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_auto_20181216_0211'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='weight',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
