# Generated by Django 2.0 on 2018-12-22 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_component_detail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component_detail',
            name='epq',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
