# Generated by Django 2.0 on 2018-12-22 08:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_auto_20181222_1534'),
    ]

    operations = [
        migrations.CreateModel(
            name='Material_detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_demand', models.PositiveIntegerField(blank=True, null=True)),
                ('holding_cost', models.PositiveIntegerField(blank=True, null=True)),
                ('setup_cost', models.PositiveIntegerField(blank=True, null=True)),
                ('usage_rate', models.PositiveIntegerField(blank=True, null=True)),
                ('lead_time', models.PositiveIntegerField(blank=True, null=True)),
                ('eoq', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('rop', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('material_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.Material')),
            ],
        ),
        migrations.AddField(
            model_name='component_detail',
            name='lead_time',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='component_detail',
            name='produce_rate',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='component_detail',
            name='usage_rate',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='component_detail',
            name='epq',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True),
        ),
    ]
