# Generated by Django 2.0 on 2019-01-01 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_auto_20190101_1836'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material_detail',
            name='name',
        ),
        migrations.AddField(
            model_name='material_detail',
            name='d_name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='material',
            name='material_detail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.Material_detail'),
        ),
    ]
