# Generated by Django 2.0 on 2019-01-01 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_auto_20190101_1843'),
    ]

    operations = [
        migrations.RenameField(
            model_name='material_detail',
            old_name='d_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='material',
            name='material_detail',
        ),
        migrations.AddField(
            model_name='material_detail',
            name='material_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.Material'),
        ),
    ]
