# Generated by Django 2.0 on 2019-01-01 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_auto_20190101_1852'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='component_detail',
            name='lead_time',
        ),
        migrations.AddField(
            model_name='component',
            name='lead_time',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
