# Generated by Django 2.0 on 2019-01-02 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0014_auto_20190101_1907'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material_detail',
            name='name',
        ),
    ]
