# Generated by Django 2.0 on 2019-01-02 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0015_remove_material_detail_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material_detail',
            name='material_name',
        ),
        migrations.DeleteModel(
            name='Material_detail',
        ),
    ]
