# Generated by Django 2.0 on 2019-01-02 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0016_auto_20190102_1459'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='component_detail',
            name='component_name',
        ),
        migrations.DeleteModel(
            name='Component_detail',
        ),
    ]
