# Generated by Django 2.0 on 2019-01-02 07:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0017_auto_20190102_1500'),
    ]

    operations = [
        migrations.CreateModel(
            name='Material_detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, null=True)),
                ('year_demand', models.PositiveIntegerField(blank=True, null=True)),
                ('holding_cost', models.PositiveIntegerField(blank=True, null=True)),
                ('setup_cost', models.PositiveIntegerField(blank=True, null=True)),
                ('usage_rate', models.PositiveIntegerField(blank=True, null=True)),
                ('lead_time', models.PositiveIntegerField(blank=True, null=True)),
                ('eoq', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('rop', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='material',
            name='material_detail',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.Material_detail'),
        ),
    ]
