# Generated by Django 2.0 on 2019-01-02 07:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0018_auto_20190102_1503'),
    ]

    operations = [
        migrations.CreateModel(
            name='Component_detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, null=True)),
                ('year_demand', models.PositiveIntegerField(blank=True, null=True)),
                ('holding_cost', models.PositiveIntegerField(blank=True, null=True)),
                ('setup_cost', models.PositiveIntegerField(blank=True, null=True)),
                ('produce_rate', models.PositiveIntegerField(blank=True, null=True)),
                ('usage_rate', models.PositiveIntegerField(blank=True, null=True)),
                ('lead_time', models.PositiveIntegerField(blank=True, null=True)),
                ('epq', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='component',
            name='lead_time',
        ),
        migrations.AddField(
            model_name='component',
            name='component_detail',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.Component_detail'),
        ),
    ]
