# Generated by Django 2.0 on 2019-01-02 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0019_auto_20190102_1509'),
    ]

    operations = [
        migrations.RenameField(
            model_name='material_detail',
            old_name='setup_cost',
            new_name='ordering_cost',
        ),
    ]
