# Generated by Django 2.0 on 2019-01-06 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0021_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component',
            name='component_detail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.Component_detail'),
        ),
    ]
