# Generated by Django 2.0 on 2019-01-18 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0022_auto_20190106_1824'),
    ]

    operations = [
        # migrations.RenameField(
        #     model_name='component',
        #     old_name='level',
        #     new_name='safety_stock',
        # ),
        # migrations.RenameField(
        #     model_name='material',
        #     old_name='level',
        #     new_name='safety_stock',
        # ),
        # migrations.RenameField(
        #     model_name='product',
        #     old_name='level',
        #     new_name='safety_stock',
        # ),
    ]
