# Generated by Django 2.0 on 2019-01-19 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0023_auto_20190119_0202'),
    ]

    operations = [
        # migrations.RenameField(
        #     model_name='product',
        #     old_name='level',
        #     new_name='safety_stock',
        # ),
    ]
