# Generated by Django 2.0 on 2019-01-19 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0024_auto_20190119_1503'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='product',
        #     name='level',
        # ),
        # migrations.AddField(
        #     model_name='product',
        #     name='safety_stock',
        #     field=models.PositiveIntegerField(blank=True, null=True),
        # ),
    ]
