# Generated by Django 2.0 on 2019-01-19 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0025_auto_20190119_1653'),
    ]

    operations = [
        # migrations.RenameField(
        #     model_name='product',
        #     old_name='safety_stock',
        #     new_name='level',
        # ),
    ]
