# Generated by Django 2.2.5 on 2019-12-18 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0028_auto_20190119_1658'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='components_required',
        ),
        migrations.RemoveField(
            model_name='product',
            name='u_feature',
        ),
        migrations.RemoveField(
            model_name='product',
            name='u_type',
        ),
        migrations.AddField(
            model_name='product',
            name='materials_required',
            field=models.ManyToManyField(blank=True, to='inventory.Material'),
        ),
        migrations.AddField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.DeleteModel(
            name='Component',
        ),
        migrations.DeleteModel(
            name='Component_detail',
        ),
    ]
