# Generated by Django 2.0 on 2018-12-13 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0003_auto_20181212_1736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='home_address',
            field=models.CharField(choices=[('N', '北部'), ('C', '中部'), ('S', '南部'), ('W', '東部')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='working_school_address',
            field=models.CharField(choices=[('N', '北部'), ('C', '中部'), ('S', '南部'), ('W', '東部')], max_length=50, null=True),
        ),
    ]
