# Generated by Django 2.0 on 2019-01-03 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0011_auto_20190104_0011'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='gender',
        ),
        migrations.AddField(
            model_name='member',
            name='age',
            field=models.CharField(choices=[('0-17', '17歲以下'), ('18-30', '18-30歲'), ('31-40', '31-40歲'), ('41-50', '41-50歲'), ('51', '51歲以上')], default='18-30', max_length=10),
        ),
    ]
