# Generated by Django 2.0 on 2019-01-03 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0012_auto_20190104_0012'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='occupation',
        ),
        migrations.AddField(
            model_name='member',
            name='gender',
            field=models.CharField(choices=[('F', '女性'), ('M', '男性')], default='F', max_length=10),
        ),
    ]
