# Generated by Django 2.0 on 2019-01-04 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0014_auto_20190104_0013'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='target_members',
        ),
        migrations.AddField(
            model_name='member',
            name='member_name',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.DeleteModel(
            name='Activity',
        ),
    ]
