# Generated by Django 2.0 on 2019-01-04 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0016_auto_20190104_1144'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='member',
            name='last_name',
        ),
    ]
