# Generated by Django 2.0 on 2019-01-06 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0018_auto_20190106_1306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='dwelling',
            field=models.CharField(choices=[('北部', '台灣北部'), ('中部', '台灣中部'), ('南部', '台灣南部'), ('東部', '台灣東部'), ('其他', '其他')], default='北部', max_length=10),
        ),
    ]
