# Generated by Django 2.0 on 2019-01-09 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0019_auto_20190106_1316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='age',
            field=models.CharField(choices=[('0-17歲', '17歲以下'), ('18-30歲', '18-30歲'), ('31-40歲', '31-40歲'), ('41-50歲', '41-50歲'), ('51歲以上', '51歲以上')], default='18-30歲', max_length=10),
        ),
        migrations.AlterField(
            model_name='member',
            name='gender',
            field=models.CharField(choices=[('女性', '女性'), ('男性', '男性')], default='女性', max_length=10),
        ),
    ]
